import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SwitchInvest – Vente Rapide Maison, Achat Immobilier Belgique | Bruxelles, Anvers, Gand',
  description: 'Vendez votre maison en 7 jours – offre sous 24-48h. Achat rapide, investissement immobilier stratégique, rénovations clés en main et gestion complète en Belgique. Sans agents, sans frais cachés. Bruxelles, Anvers, Gand, Liège.',
  keywords: [
    'vente rapide maison Belgique',
    'achat maison rapide Bruxelles',
    'investissement immobilier Belgique',
    'gestion immobilière Bruxelles',
    'achat immobilier sans agent',
    'vendre maison en l\'état',
    'rénovation immobilière Belgique',
    'investissement locatif Belgique',
    'immobilier Anvers',
    'immobilier Gand',
    'vente maison 7 jours',
    'achat propriété Belgique',
    'gestion locative Bruxelles',
    'real estate investment Belgium',
    'property management Brussels',
    'sell house fast Belgium',
    'vastgoed investering België',
    'huis verkopen België',
    'onroerend goed Brussel',
    'immobilien Belgien',
  ],
  alternates: {
    canonical: '/',
    languages: {
      'fr-BE': '/',
      'nl-BE': '/',
      'de-BE': '/',
      'en-BE': '/',
    },
  },
  openGraph: {
    title: 'SwitchInvest – Vente Rapide Maison & Investissement Immobilier Belgique',
    description: 'Offre sous 24-48h, clôture en 7 jours. Achat rapide, investissement stratégique, rénovations clés en main. Sans agents, sans frais cachés. Bruxelles, Anvers, Gand.',
    url: 'https://switchinvest.be',
    images: ["/images/og-image.jpg"],
    locale: 'fr_BE',
    type: 'website',
    siteName: 'SwitchInvest',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SwitchInvest – Vente Rapide & Investissement Immobilier Belgique',
    description: 'Vendez en 7 jours | Investissement stratégique | Gestion complète',
    images: ['/images/twitter-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};
